#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/security
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#    properties:
#      hibernate:
#        format-sql: false
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: jamil
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect




     